##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.5.0-RC5] date: [Fri Jun 06 10:48:25 CEST 2025]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = orcos


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# Library name
LIB_NAME = liborcos.a

RTT_SOURCES = \
liborcos/RTT/SEGGER_RTT.c \
liborcos/RTT/SEGGER_RTT_printf.c

# Library sources
LIB_SOURCES = \
$(RTT_SOURCES) \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_adc.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_adc_ex.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_dma.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_dma_ex.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_rcc.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_rcc_ex.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_cortex.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_flash.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_flash_ex.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_gpio.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_exti.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_pwr.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_pwr_ex.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_gtzc.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_icache.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_lptim.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_rtc.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_rtc_ex.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_spi.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_spi_ex.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_tim.c \
liborcos/Drivers/STM32U3xx_HAL_Driver/Src/stm32u3xx_hal_tim_ex.c \
liborcos/Src/calc.c \
liborcos/Src/fonts.c \
liborcos/Src/func.c \
liborcos/Src/io.c \
liborcos/Src/keyboard.c \
liborcos/Src/orcos.c \
liborcos/Src/power.c \
liborcos/Src/rtc.c \
liborcos/Src/sharp.c \
liborcos/Src/sharp_graphics.c \
liborcos/Src/sharp_lowlevel.c

# C sources
C_SOURCES =  \
demo/Src/main.c \
demo/Src/stm32u3xx_it.c \
demo/Src/stm32u3xx_hal_msp.c \
demo/Src/system_stm32u3xx.c \
demo/Src/sysmem.c \
demo/Src/syscalls.c

# ASM sources
ASM_SOURCES =  \
startup_stm32u385xx.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m33

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32U385xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-Idemo/Inc \
-Iliborcos/Inc \
-Iliborcos/Drivers/STM32U3xx_HAL_Driver/Inc \
-Iliborcos/Drivers/STM32U3xx_HAL_Driver/Inc/Legacy \
-Iliborcos/Drivers/CMSIS/Device/ST/STM32U3xx/Include \
-Iliborcos/Drivers/CMSIS/Include \
-Iliborcos/RTT \


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2 -DDEBUG=$(DEBUG)
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32U385xx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
LIB_OBJECTS = $(patsubst %.c,$(BUILD_DIR)/%.o,$(LIB_SOURCES))
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES) $(dir $(LIB_SOURCES))))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	@mkdir -p $(@D)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
$(BUILD_DIR)/$(LIB_NAME): $(LIB_OBJECTS)
	$(PREFIX)ar rcs $@ $^

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) $(BUILD_DIR)/$(LIB_NAME) Makefile
	$(CC) $(OBJECTS) -L$(BUILD_DIR) -lorcos $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir -p $@

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
	-rm -f $(LIB_NAME)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

.PHONY: probe-rs docs

.PHONY: docs
docs:
	doxygen Doxyfile
	@echo "Docs generated in docs/html/index.html"

clean-docs:
	rm -rf docs/

publish-docs: docs
# Note: git worktree requires git >= 2.5
	git worktree add /tmp/gh-pages gh-pages  # Create gh-pages worktree
	rm -rf /tmp/gh-pages/docs/*              # Clear old files
	cp -r docs/html/* /tmp/gh-pages/docs     # Copy new docs
	cd /tmp/gh-pages && \
	git add docs/* && \
	if ! git diff-index --quiet HEAD --; then \
	  git commit -m "Deploy Doxygen docs" && \
	  git push origin gh-pages; \
	else \
	  echo "No documentation changes to commit"; \
	fi
	git worktree remove /tmp/gh-pages       # Cleanup

probe-rs:
	(cd probe-rs && cargo build --release)

flash: build/$(TARGET).elf probe-rs
	probe-rs/target/release/probe-rs run --connect-under-reset --chip STM32U385RGTx build/$(TARGET).elf

# *** EOF ***
